language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.cache/bower
    - $HOME/.composer/cache
    - $HOME/.npm
    - /tmp/phantomjs
    - tools

env:
  global:
    - CORE_BRANCH=stable10
    - APP_NAME=customgroups
  matrix:
    - DB=mysql

branches:
  only:
    - master

addons:
  apt: &common_apt
    packages:
      # Needed for xmllint
      - libxml2-utils

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB

  # Add some output debugging information
  - cd ../core
  - ./occ check
  - ./occ status
  - ./occ app:list

install:
- sh -c "if [ '$TEST' = 'test-acceptance' ]; then git clone https://github.com/owncloud/testing.git apps/testing; fi"
- sh -c "if [ '$TEST' = 'test-acceptance' ]; then php occ app:enable testing; fi"

script:
  - cd apps/$APP_NAME/
  - make $TEST

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - php: 7.1
      env: DB=mysql;CORE_BRANCH=master
    - php: 7.2
      env: DB=mysql;CORE_BRANCH=master
    # PHP unit tests with mySQL
    - php: 7.1
      env: DB=mysql;TEST=test-php;CORE_BRANCH=master
    - php: 5.6
      env: DB=mysql;TEST=test-php
    # PHP unit tests with pgSQL
    - php: 7.1
      env: DB=pgsql;TEST=test-php;CORE_BRANCH=master
    - php: 5.6
      env: DB=pgsql;TEST=test-php
    # Code checker / syntax
    - php: 7.1
      env: DB=mysql;TEST=test-codecheck;CORE_BRANCH=master
    - php: 5.6
      env: DB=mysql;TEST=test-codecheck
    # Code checker (deprecations only, allowed to fail)
    - php: 5.6
      env: DB=mysql;TEST=test-codecheck-deprecations
    # Javascript tests
    - php: 7.1
      env: DB=mysql;TEST=test-js;CORE_BRANCH=master
    - php: 5.6
      env: DB=mysql;TEST=test-js
    # Acceptance tests
    - php: 7.1
      env: DB=mysql;TEST=test-acceptance;CORE_BRANCH=master
      addons:
        apt: *common_apt
    - php: 5.6
      env: DB=mysql;TEST=test-acceptance;CORE_BRANCH=stable10
      addons:
        apt: *common_apt
  allow_failures:
    - env: DB=mysql;TEST=test-codecheck-deprecations
  fast_finish: true
